#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gesdinet_jwt_refresh_token:
    path: /api/authentification/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
