# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $facebookId: '%env(resolve:FACEBOOK_ID)%'
      $facebookSecret: '%env(resolve:FACEBOOK_SECRET)%'
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

  App\Http\Api\Controller\:
    resource: '../src/Http/Api/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Http\App\Controller\:
    resource: '../src/Http/App/Controller'
    tags: [ 'controller.service_arguments' ]

  App\Application\Authentification\Auth\Listenners\LoginListenner:
    tags:
      - { name: 'kernel.event_listener' , event: 'security.authentication.success' }
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Http\Api\OpenApi\Authentification\OpenAuthentificationApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\Http\Api\OpenApi\Authentification\OpenAuthentificationApiFactory.inner' ]
    autoconfigure: false

  App\Http\Api\OpenApi\Profile\OpenProfileApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\Http\Api\OpenApi\Profile\OpenProfileApiFactory.inner' ]
    autoconfigure: false

  App\Http\Api\OpenApi\QrCode\OpenQrCodeApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\Http\Api\OpenApi\QrCode\OpenQrCodeApiFactory.inner' ]
    autoconfigure: false

  App\Http\Api\OpenApi\SubscriptionPlan\OpenSubscriptionPlanApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\Http\Api\OpenApi\SubscriptionPlan\OpenSubscriptionPlanApiFactory.inner' ]
    autoconfigure: false

  App\Http\Api\OpenApi\EnableCountry\OpenEnableCountryApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\Http\Api\OpenApi\EnableCountry\OpenEnableCountryApiFactory.inner' ]
    autoconfigure: false

  App\Http\Api\OpenApi\Cards\OpenCardApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: [ '@App\Http\Api\OpenApi\Cards\OpenCardApiFactory.inner' ]
    autoconfigure: false

